from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum


class MessageCode(StrEnum):
    INVALID_DURATION = "INVALID_DURATION"
    NON_MINUTE_ALIGNED_WINDOW = "NON_MINUTE_ALIGNED_WINDOW"
    EMPTY_CONSTRAINT_GROUP = "EMPTY_CONSTRAINT_GROUP"
    INVALID_TIME_WINDOW = "INVALID_TIME_WINDOW"
    PLAN_NOT_FOUND = "PLAN_NOT_FOUND"
    CONSTRAINT_GROUP_NOT_FOUND = "CONSTRAINT_GROUP_NOT_FOUND"
    TIME_WINDOW_NOT_FOUND = "TIME_WINDOW_NOT_FOUND"
    SYSTEM_CONSTRAINT_DIRECT_EDIT_FORBIDDEN = "SYSTEM_CONSTRAINT_DIRECT_EDIT_FORBIDDEN"

    INVALID_MASTER_PLAN = "INVALID_MASTER_PLAN"
    ORPHAN_PLAN = "ORPHAN_PLAN"
    PLAN_SUBTYPE_MISMATCH = "PLAN_SUBTYPE_MISMATCH"
    CHAIN_INVARIANT_VIOLATION = "CHAIN_INVARIANT_VIOLATION"
    CONSTRAINT_INVARIANT_VIOLATION = "CONSTRAINT_INVARIANT_VIOLATION"

    INVALID_INCOMPLETE_TASKS_BLOCK_ASSIGNMENT = "INVALID_INCOMPLETE_TASKS_BLOCK_ASSIGNMENT"
    RUN_STARTED_AT_MISMATCH = "RUN_STARTED_AT_MISMATCH"
    REPETITION_COUNT_DECREASE_AFTER_GENERATION = "REPETITION_COUNT_DECREASE_AFTER_GENERATION"

    NO_VALID_WINDOW_FOR_TASK = "NO_VALID_WINDOW_FOR_TASK"
    PRECEDENCE_IMPOSSIBLE = "PRECEDENCE_IMPOSSIBLE"
    INSUFFICIENT_TOTAL_CAPACITY = "INSUFFICIENT_TOTAL_CAPACITY"
    MINIMUM_CHUNK_SIZE_IMPOSSIBLE = "MINIMUM_CHUNK_SIZE_IMPOSSIBLE"
    TASK_OVERLAP_REQUIRED = "TASK_OVERLAP_REQUIRED"
    SOLVER_FAILED_TO_FIND_FEASIBLE_ASSIGNMENT = "SOLVER_FAILED_TO_FIND_FEASIBLE_ASSIGNMENT"

    SOLVER_LIMIT_REACHED = "SOLVER_LIMIT_REACHED"
    FEASIBLE_NOT_PROVEN_OPTIMAL = "FEASIBLE_NOT_PROVEN_OPTIMAL"
    HEURISTIC_FEASIBLE = "HEURISTIC_FEASIBLE"


@dataclass(frozen=True)
class ServiceMessage:
    code: MessageCode
    message: str
    details: dict[str, str] = field(default_factory=dict)  # pyright: ignore[reportUnknownVariableType]


class WrongPlanTypeError(TypeError):
    """Raised when a service receives a plan of the wrong subtype."""


class ServiceTransactionAborted(Exception):
    """Raised inside transaction() to roll back; convert to fail(...) at the service boundary."""

    def __init__(self, errors: tuple[ServiceMessage, ...]) -> None:
        self.errors = errors
