"""create plan and child chain tables

Revision ID: be7d178b7c5a
Revises: 
Create Date: 2026-06-12 15:09:47.240886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7d178b7c5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_kind', sa.Enum('GOAL', 'TASK', 'REPETITION', name='plankind', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('cloned_from_id', sa.Uuid(), nullable=True),
    sa.Column('clone_status', sa.Enum('TEMPLATE', 'LINKED', 'DETACHED', 'NOT_CLONED', name='clonestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("NOT is_master OR plan_kind = 'GOAL'", name=op.f('ck_plan_master_is_goal')),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['plan.plan_id'], name=op.f('fk_plan_cloned_from_id_plan')),
    sa.ForeignKeyConstraint(['parent_id'], ['plan.plan_id'], name=op.f('fk_plan_parent_id_plan')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_plan'))
    )
    op.create_index('uq_plan_is_master', 'plan', ['is_master'], unique=True, sqlite_where=sa.text('is_master = 1'))
    op.create_table('goal_plan',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], name=op.f('fk_goal_plan_plan_id_plan')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_goal_plan'))
    )
    op.create_table('repetition_plan',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('repeat_mode', sa.Enum('MANUAL_COUNT', 'DATE_RANGE', name='repeatmode', native_enum=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('manual_count', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_root_id', sa.Uuid(), nullable=False),
    sa.Column('default_instance_critical', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], name=op.f('fk_repetition_plan_plan_id_plan')),
    sa.ForeignKeyConstraint(['template_root_id'], ['plan.plan_id'], name=op.f('fk_repetition_plan_template_root_id_plan')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_repetition_plan'))
    )
    op.create_table('task_plan',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('divisible', sa.Boolean(), nullable=False),
    sa.Column('minimum_chunk_size_minutes', sa.Integer(), nullable=False),
    sa.Column('user_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], name=op.f('fk_task_plan_plan_id_plan')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_task_plan'))
    )
    op.create_table('goal_child_chain',
    sa.Column('goal_child_chain_id', sa.Uuid(), nullable=False),
    sa.Column('parent_goal_id', sa.Uuid(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_goal_child_chain_sort_order_non_negative')),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goal_plan.plan_id'], name=op.f('fk_goal_child_chain_parent_goal_id_goal_plan')),
    sa.PrimaryKeyConstraint('goal_child_chain_id', name=op.f('pk_goal_child_chain'))
    )
    op.create_table('goal_child_chain_item',
    sa.Column('goal_child_chain_item_id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Uuid(), nullable=False),
    sa.Column('child_plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_goal_child_chain_item_position_non_negative')),
    sa.ForeignKeyConstraint(['chain_id'], ['goal_child_chain.goal_child_chain_id'], name=op.f('fk_goal_child_chain_item_chain_id_goal_child_chain')),
    sa.ForeignKeyConstraint(['child_plan_id'], ['plan.plan_id'], name=op.f('fk_goal_child_chain_item_child_plan_id_plan')),
    sa.PrimaryKeyConstraint('goal_child_chain_item_id', name=op.f('pk_goal_child_chain_item')),
    sa.UniqueConstraint('child_plan_id', name=op.f('uq_goal_child_chain_item_child_plan_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_child_chain_item')
    op.drop_table('goal_child_chain')
    op.drop_table('task_plan')
    op.drop_table('repetition_plan')
    op.drop_table('goal_plan')
    op.drop_index('uq_plan_is_master', table_name='plan', sqlite_where=sa.text('is_master = 1'))
    op.drop_table('plan')
    # ### end Alembic commands ###
